### ISSUE TITLE
docs for lein-localrepo not displaying

### ISSUE THREAD

**Issue by uvtc** [kumarshantanu/lein-localrepo#11]
When I run `lein help localrepo`, all I get returned is:

~~~
~/temp/some-app$ lein help localrepo
Work with local Maven repository

Arguments: ([_] [_ command & args])
~~~

I expected to see a list of subcommands available with summaries.

Setup:

  * Debian GNU/Linux
  * Clojure 1.8.0
  * Leiningen 2.7.1 on Java 1.8.0_131 OpenJDK 64-Bit Server VM
  * in my project.clj: `:plugins [[lein-localrepo "0.5.3"]]`

**Comment by kumarshantanu** [comment]
Thanks for reporting the issue. A fix would involve updating the docstring of `leiningen.localrepo/localrepo` to list the commands. I would welcome pull requests in case anybody wants to submit a fix.
