### ISSUE TITLE
boot-localrepo?

### ISSUE THREAD

**Issue by seancorfield** [kumarshantanu/lein-localrepo#12]
`lein-localrepo` is a very useful tool. It would be nice if there was a `boot-localrepo` for Boot users. I can't remember whether I've seen you working with Boot (sorry), so I'm happy to help out -- or to take this on if you don't have the time/inclination?

**Comment by seancorfield** [comment]
Interestingly, the way `lein-localrepo` is written, us Boot folks could invoke it directly from the command line:

    boot -d leiningen -d lein-localrepo  call -e "(require '[leiningen.localrepo :as lr])" -e '(lr/localrepo nil "install" "hello.jar" "world/hello" "1.0.0")'

Not quite as convenient, but the equivalent of:

    lein localrepo install hello.jar world/hello 1.0.0

**Comment by kumarshantanu** [comment]
@seancorfield That's interesting! Unfortunately, I don't know Boot enough to be able to do an effective job at making boot-localrepo, but I am happy to support in whatever way I can if you (or anybody else) want to take this up.

**Comment by seancorfield** [comment]
https://github.com/seancorfield/boot-localrepo
